### ISSUE TITLE
Thesis TODOs

### ISSUE THREAD

**Issue by informusica** [brussee/thesis#1]
- [x] Results chapter: first write rationale, setup & outcomes of various experiments. Only then add the figures.
- [x] Then Results => Conclusions also considering original research questions. Future work only as backlog.
- [x] Based on Results back to 'Tribler for mobile' & Design chapters
- [x] Implementation (& Future Work)

**Comment by brussee** [comment]
- [x] Problem description chapter reshuffle, ALLEEN duplicates deleten!
- [x] Problem description chapter uitbreiden. Niet deleten!
- [x] Geen enkele bullet meer, alleen hele zinnen in problem description chapter.
- [x] Egaal aanvullen van problem description chapter.

**Comment by informusica** [comment]
- Use the order above in filling chapter content
- Set strict milestones per day and drop whatever can't be fixed by that milestone until the next iteration
- Don't forget to plan for LaTeX and presentation preparations
- When stalling on a particular point for too long, make a note but also drop and continue until the next iteration

**Comment by informusica** [comment]
And **don't fix problems of others** until after your defense. :)

**Comment by brussee** [comment]
FYI: de brief van de decaan lag gister in de brievenbus met goed nieuws!
(Nu fase 2: formulieren naar de DUO.)

**Comment by brussee** [comment]
- [x] for chapters with unstructured content, reshuffle content WITHOUT REWRITING OR ADDING CONTENT.

Ma. 21:
- [x] Conclusions & Future work iteratie; considering original research questions.
- [x]  Based on Results back to 'Tribler for mobile' & Design chapters.

Di. 22:
- [x] Implementation (& Future Work) iteratie.
- [x] Add https://github.com/Tribler/tribler/issues/2231#issuecomment-260631346
- [x] Results chapter iteratie.
- [x] Add device specs table.
- [x] Feedback Johan.

Wo. 23:
- [x] Rewrite Intro to management summary.
- [x] Tribler functionality chapter iteratie.

Do. 24:
- [x] Print out.

---
- [x] Split: Java GUI, Core started
- [ ] Possible additional experiment: measure transfer time between various phones of 25MB clips or show power consumption during phone-to-phone exchange (max. 1 day experiment)
- [ ] Possible additional experiment: Power consumption experiment (battery drain, 4x Galaxy Nexus)

**Comment by brussee** [comment]
- [x] Merge design principles into requirements
- [x] Sequence numbering of requirements
- [x] Describe new architecture diagram (rework existing text) (find orig fig)
- [x] Add intro of new architecture fig. in implementation
- [x] Dedup intro
- [x] Improve quality of intro (underline what can be improved first)
- [x] Citations in intro + BIB

**Comment by brussee** [comment]
Zo. 11
- [x] Higher level conclusions
- [x] Future research plus setup
- [x] Correct flow of entire thesis (connecting sentences, questions and answers over hele boog)
- [x] Intro of Results chapter met rode lijn: problem desc.; grote plaatje: key questions en reden voor alle experiments
- [x] Rewrite API results
- [x] Rewrite CPU utilization
- [x] Rewrite testing and coverage
- [x] Improve intro
- [x] Citations in intro
- [x] Improve problem description
- [x] Reference figure in problem description
- [x] Describe all screenshots
- [x] Link dependency tree to sys arch & build tool-chain
- [ ] Build toolchain beter inleiden
- [ ] Link sys arch to build tool-chain
- [x] Improve about Tribler in depth and link problem desc
- [x] Citations in problem description
- [x] Citations in design
- [x] Citations in implementation
- [x] Citations in results
- [x] Citations in conclusions and future work
- [x] Stats PRs fill-in
- [x] Update stats table about src

Ma. 12
- [x] Start presentatie maken

Di. 13
- [ ] Give presentation

**Comment by synctext** [comment]
presentation draft ?

**Comment by brussee** [comment]
@synctext https://github.com/brussee/thesis/blob/master/defence/presentation.pdf
